name: Build latest from main
 
on:
  push:
    branches: [ main ] # This watches the branch called "main"
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: craftech-io/package-action@v3.1.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile.prod
        image_name: jnega-test-img # Must be unique in the mlibrary org
        tags: |
          latest
          ${{ github.sha }}
